# -*- coding: utf-8 -*-
# Programme and faculty, transcribed from
# "ESA Focus Meeting 2027 - Preliminary Program v7.docx" (preliminary, 2026-10-09).
# Rows are (time range, duration, title, [talks], note, is_break). A talk may carry
# its speaker in <i>...</i>. A range of "TBC" renders as a row without a time.

DAY1 = ("1", "Friday, 10 September 2027", "08:00&ndash;16:45", [
 ("08:00&ndash;09:00","60 min","Session 1 &middot; Anterosuperior tears: repairable massive tears",
  ["Open versus arthroscopic repair: which is the proper arthroscopic repair?",
   "&ldquo;Relive&rdquo;: How I repair it",
   "Augmentation techniques",
   "Management of the pseudoparetic shoulder",
   "Discussion"],
  "Format|10-minute presentations, each followed by 5 minutes of discussion", False),
 ("09:00&ndash;10:00","60 min","Session 2 &middot; Anterosuperior tears: irreparable tears",
  ["Which tendon transfer? Evidence-based indications and outcomes",
   "&ldquo;Relive&rdquo;: Pectoralis minor transfer",
   "&ldquo;Relive&rdquo;: Pectoralis major transfer",
   "&ldquo;Relive&rdquo;: Latissimus dorsi transfer"],
  "Expert debate|Which tendon transfer? 10-minute presentations, each followed by 5 minutes of discussion", False),
 ("10:00&ndash;10:30","30 min","Session 3 &middot; Case-based discussion", [],
  "Format|Two clinical cases, 15 minutes each", False),
 ("10:30&ndash;11:00","30 min","Coffee break and industry visit", [], "", True),
 ("11:00&ndash;12:00","60 min","Session 4 &middot; Posterosuperior tears: repairable massive tears",
  ["Treatment algorithm: evidence-based medicine",
   "Biological augmentation techniques: footprint preservation, growth factors and stem cells",
   "Biceps augmentation: techniques and outcomes",
   "Patch augmentation: technique and outcomes",
   "Discussion"],
  "Format|10-minute presentations, each followed by 5 minutes of discussion", False),
 ("12:00&ndash;12:15","15 min","Session 5 &middot; Opening and greetings", [], "", False),
 ("12:15&ndash;13:15","60 min","Lunch break and industry visit", [], "", True),
 ("13:15&ndash;14:15","60 min","Session 6 &middot; Posterosuperior tears: irreparable tears",
  ["Functional repair",
   "Superior capsular reconstruction: long head of the biceps",
   "Superior capsular reconstruction: fascia lata autograft",
   "Tendon transfers: latissimus dorsi versus lower trapezius"],
  "Format|10-minute presentations, each followed by 5 minutes of discussion", False),
 ("14:15&ndash;14:45","30 min","Session 7 &middot; Case-based discussion", [],
  "Format|Two clinical cases, 15 minutes each", False),
 ("14:45&ndash;15:15","30 min","Coffee break and industry visit", [], "", True),
 ("15:15&ndash;15:45","30 min","Session 8 &middot; Keynote lecture",
  ["The Future of Rotator Cuff Reconstruction <i>Speaker to be confirmed</i>"],
  "Format|A 20-minute presentation and 10 minutes of free discussion", False),
 ("15:45&ndash;16:15","30 min","Session 9 &middot; Keynote lecture",
  ["Massive Rotator Cuff Tears: Repair, Reconstruct, Transfer or Replace? <i>Emilio Calvo, to be confirmed</i>"],
  "Format|A 20-minute presentation and 10 minutes of free discussion", False),
 ("16:15&ndash;16:45","30 min","Session 10 &middot; Keynote lecture",
  ["Beyond the Scalpel: Metabolic Health as a Surgical Variable <i>Speaker to be confirmed</i>"],
  "Format|A 20-minute presentation and 10 minutes of free discussion", False),
])

DAY2 = ("2", "Saturday, 11 September 2027", "08:30&ndash;15:30", [
 ("08:30&ndash;09:45","75 min","Session 11 &middot; When arthroscopy is no longer enough",
  ["Indications: patient profile (massive tears, retears, pseudoparalysis)",
   "Implant design and biomechanics: planning for function",
   "From preoperative planning to PSI: bringing the plan into the operating theatre",
   "Indications for augmenting with tendon transfers",
   "Complications and management",
   "Discussion"],
  "Format|10-minute presentations, each followed by 5 minutes of discussion", False),
 ("09:45&ndash;10:45","60 min","Session 12 &middot; Case-based discussion", [],
  "Format|Four clinical cases, 15 minutes each", False),
 ("10:45&ndash;11:15","30 min","Coffee break and industry visit", [], "", True),
 ("11:15&ndash;12:30","75 min","Session 13 &middot; Arthroplasty",
  ["How to improve rotations after reverse shoulder arthroplasty",
   "&ldquo;Relive&rdquo;: Subscapularis-sparing deltopectoral approach: technique, tips and tricks",
   "&ldquo;Relive&rdquo;: Anterosuperior approach: technique, tips and tricks",
   "&ldquo;Relive&rdquo;: Navigation-assisted reverse shoulder arthroplasty",
   "&ldquo;Relive&rdquo;: Robotic-assisted reverse shoulder arthroplasty"],
  "Format|10-minute presentations, each followed by 5 minutes of discussion", False),
 ("12:30&ndash;13:30","60 min","Lunch break and industry visit", [], "", True),
 ("13:30&ndash;14:00","30 min","Session 14 &middot; Case-based discussion", [],
  "Format|Two clinical cases, 15 minutes each", False),
 ("14:00&ndash;14:30","30 min","Session 15 &middot; Rehabilitation", [],
  "Format|Two talks, to be announced, followed by discussion", False),
 ("14:30&ndash;15:30","60 min","Session 16 &middot; Grand finale debate",
  ["Superior capsular reconstruction <i>Teruhisa Mihata</i>",
   "Lower trapezius transfer <i>Bassem Elhassan</i>",
   "Functional (partial) repair <i>Emilio Calvo</i>",
   "Reverse shoulder arthroplasty <i>Felix Savoie III</i>",
   "Discussion"],
  "Moderators|Emmanouil Brilakis and Maristella Saccomanno &middot; What is the best treatment for the 60-year-old active patient with an irreparable posterosuperior rotator cuff tear? Invitations pending confirmation.", False),
])

# name, role or country ("" when ESSKA has not given one); order as the chairs sign the letter
CHAIRS = [("Emmanouil Brilakis","ESSKA Shoulder Section Chair"),
          ("Maristella Francesca Saccomanno","Scientific Chair"),
          ("Alfonso Maria Romano","Scientific Chair"),
          ("Nezih Ziroglu","Local Chair"),
          ("Kerem Bilsel","Local Chair"),
          ("Bar&#305;&#351; Kocao&#287;lu","Local Chair")]

# proposed invited faculty, invitations pending confirmation (programme v7)
PROPOSED = [("Teruhisa Mihata","Japan"),("Bassem Elhassan","US"),
            ("Emilio Calvo","Spain"),("Felix Savoie III","US"),
            ("Jean Kany",""),("Samuel Antu&ntilde;a","Spain"),
            ("Jean-David Werthel","France"),("Abdul-ilah Hachem","Spain"),
            ("Miguel Ruiz Ib&aacute;n","Spain")]
