# -*- coding: utf-8 -*-
# Programme and faculty, transcribed from Rome_2027_Programme_with_Faculty_v1.xlsx

DAY1 = ("1", "Friday, 8 October 2027", "09:00&ndash;18:00", [
 ("09:00&ndash;09:15","15 min","Welcome and Introduction",
  ["Opening remarks, ESSKA","Introduction of faculty and course essentials",
   "Introduction of the new ESSKA Section and its activity"],
  "Presented by|Michael Hantes, Bruno Violante and Pawe&#322; Skowronek", False),
 ("09:15&ndash;10:45","90 min","Session 1: Decision Making",
  ["Patient expectations after TKA","Painful TKA: diagnostic algorithm",
   "RTKA: results and complications","Robotic RTKA: state of the art",
   "Selected component revision in RTKA","Role of the plastic surgeon in the multioperated knee",
   "The RTKA workflow: steps to make the correct decision"],
  "Format|Seven 10-minute talks, followed by 20 minutes of discussion around the case &ldquo;Nightmare revision: what would you do?&rdquo;", False),
 ("10:45&ndash;11:15","30 min","Coffee break", [], "", True),
 ("11:15&ndash;12:45","90 min","Session 2: Basics of Revision",
  ["Surgical exposure in RTKA","Implant removal in RTKA",
   "Coronal alignment in revision TKA: keep mechanical",
   "Coronal alignment in revision TKA: looking to anatomic",
   "Reconstructing the joint line in revision TKA","The third space in RTKA",
   "Revision uni knee: tips and tricks"],
  "Format|Seven 10-minute talks, followed by 20 minutes of case-based discussion", False),
 ("12:45&ndash;13:45","60 min","Lunch", [], "", True),
 ("13:45&ndash;15:15","90 min","Session 3: Fixation and Bone Defects",
  ["Classification of bone defects","Two-zone fixation in RTKA",
   "Metaphyseal fixation: cones","Metaphyseal fixation: sleeves",
   "How to use wedges and blocks","Stems: cemented vs porous, short vs diaphyseal",
   "Porous implant in RTKA"],
  "Format|Seven 10-minute talks, followed by a 20-minute discussion of a difficult bone-loss case", False),
 ("15:15&ndash;15:45","30 min","Coffee break", [], "", True),
 ("15:45&ndash;17:15","90 min","Session 4: Stability and Ligament Balance",
  ["Level of constraint in RTKA","Management of patellar instability",
   "Sagittal plane instability: recurvatum and flexion instability",
   "Coronal plane and mid-flexion instability","Basics of megaprostheses",
   "Management of patella fracture, quadriceps and patellar tendon rupture in RTKA",
   "The stiff knee in revision"],
  "Format|Seven 10-minute talks, followed by 20 minutes of case discussion on instability and constraint", False),
 ("17:15&ndash;18:00","45 min","Day 1 Interactive Finale",
  ["Integrated complex aseptic revision cases"],
  "Format|Three short cases connecting decision-making, fixation, bone loss and stability, with faculty voting and take-home messages", False),
])

DAY2 = ("2", "Saturday, 9 October 2027", "08:30&ndash;14:00", [
 ("08:30&ndash;09:30","60 min","Session 5: Osteotomy Techniques in RTKA",
  ["TKA in extra-articular deformities","Osteotomies around the knee in RTKA",
   "Osteotomy techniques to remove difficult knee implants (TTA)"],
  "Format|Three 10-minute talks, followed by 30 minutes of case-based discussion", False),
 ("09:30&ndash;11:00","90 min","Session 6A: PJI Diagnosis and Decision Making",
  ["Current diagnostic criteria: ICM/EBJIS, unified: where do we stand? <i>Daniel P&eacute;rez-Prieto</i>",
   "Emerging biomarkers and differential diagnosis with aseptic loosening <i>Andrea Sambri</i>",
   "Low-grade and culture-negative PJI: the diagnostic challenge <i>Antonio Pellegrini</i>"],
  "Format|Ten-minute presentations, followed by discussion", False),
 ("11:00&ndash;11:30","30 min","Coffee break", [], "", True),
 ("11:30&ndash;13:00","90 min","Session 6B: PJI Treatment and Reconstruction",
  ["One-stage revision: technique and outcomes <i>Juan Carlos Mart&iacute;nez-Pastor</i>",
   "Two-stage revision: spacers and timing of reimplantation <i>Ricardo Sousa</i>",
   "Management of recurrent PJI and re-revision for infection <i>Antonio Pellegrini</i>",
   "Why do we not want a one- versus two-stage crossfire any more? <i>All faculty</i>"],
  "Format|The second 90-minute PJI block, including soft-tissue reconstruction", False),
 ("13:00&ndash;13:45","45 min","PJI Interactive Finale: Nightmare Infected Revision",
  ["Difficult cases combining bone defect and infection <i>Massimiliano De Paolis and Roland Becker</i>",
   "Final round table with all faculty"],
  "Format|Case-based multidisciplinary discussion with faculty voting", False),
 ("13:45&ndash;14:00","15 min","Final Take-Home Messages and Closing",
  ["Key messages from all sessions"], "", False),
])

INVITED = [("Javad Parvizi","US"),("Antonia Chen","US"),("Bryan Springer","US"),
 ("Michael Meneghini","US"),("David Parker","Australia"),("Nicolaas Budhiparama","Indonesia"),
 ("Jiis Van Ellemondt","Netherlands"),("Sebastien Lustig","France"),("Fares Haddad","UK")]

# rows 38-69 are Surname | Firstname; rows 70-80 are Firstname | Surname
FACULTY = [("Pawe&#322; Skowronek","Poland"),("Guillaume Demey","France"),("Bruno Violante","Italy"),
 ("Steffen Schr&ouml;ter","Germany"),("Daniel Perez Prieto","Spain"),("Elvire Servien","France"),
 ("Alan Ivkovic","Croatia"),("Trifon Totlis","Greece"),("Daniel Guenther","Germany"),
 ("Artur Kroell","Switzerland"),("James Harty","Ireland"),("Giuseppe Umile Longo","Italy"),
 ("Mikhail Salzmann","Germany"),("Christos Koutserimpas","Greece"),("George Mihai Avram","Romania"),
 ("Philippe Van Overschelde","Belgium"),("Bartosz Maciag","Poland"),("Antonio Klasan","Austria"),
 ("Theofilos Karachalios","Greece"),("Nane Kort","Netherlands"),("Mladen Miskulin","Croatia"),
 ("Bruce Gomberg","USA"),("Christian Schaller","Germany"),("Patrick Sadoghi","Austria"),
 ("Geert Meermans","Belgium"),("Luigi Capasso","Italy"),("Raghbir Khakha","UK"),
 ("Vlad Predescu","Romania"),("Ricardo Sousa","Portugal"),("Michael Engl","Austria"),
 ("Pier Indelli","Italy"),("Reha Tandogan","Turkey"),("Michael Hirschmman","Switzerland"),
 ("Roland Becker","Germany"),("Andrea Sambri",""),("Antonio Pellegrini",""),
 ("Juan Carlos Mart&iacute;nez-Pastor",""),("Massimiliano De Paolis",""),
 ("Marta Sabater",""),("Ali Al Belooshi","")]

SUMMARY = [("10&#8239;h&#8239;45","Scientific programme","excluding breaks"),
           ("3&#8239;h&#8239;45","Dedicated to PJI","two 90-min sessions + case finale"),
           ("10 min","Standard lecture","discussion at the end of each session"),
           ("TBC","Faculty","details to follow")]
